### ISSUE TITLE
Arch dependencies and coref fail in named instance

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#614] opened 2019-08-09 10:57 UTC
What is the used ANNIS version?

4.0.0-beta.2 (rev. 92cc9d6df4, built 2019-07-22 16:05:33)

What browser and operating system did you use?

Win 10 64, Chrome

What steps will reproduce the problem?
1. Use a named instance, tested on GU scriptorium/ instance with a corpus using arch dependencies (and segmentations, not sure if that's important)
2. Run an AQL query retrieving some dependencies, e.g.:

```
pos=‎"V‎" ->dep[func=‎"nsubj‎"] lemma=‎"ⲁⲛⲟⲕ‎"
```

3. In the normal URL without an instance, this produces this query URL:

host.../annis.../#_q=cG9zPSJWIiAtPmRlcFtmdW5jPSJuc3ViaiJdIGxlbW1hPSLisoHispvisp_ispUi&ql=aql&_c=c2hlbm91dGUuZm94&cl=5&cr=5&s=0&l=10&_seg=Ym05eWJWOW5jbTkxY0E

But if run inside .../scriptorium/, the following link 

host.../annis.../scriptorium/#_q=cG9zPSJWIiAtPmRlcFtmdW5jPSJuc3ViaiJdIGxlbW1hPSLisoHispvisp_ispUi&ql=aql&_c=c2hlbm91dGUuZm94&cl=5&cr=5&s=0&l=10&_seg=Ym05eWJWOW5jbTkxY0E

The query runs fine, but expanding the dependency vis loads another copy of the ANNIS interface inside the expandable vis frame (see screenshot). This doesn't happen without the instance suffix.

![image](https://user-images.githubusercontent.com/2188635/62774530-f4f13f80-ba72-11e9-9566-70b99fc8e2dc.png)

I remember we had some kind of issue with `#` in the URL killing the dependency vis, but both URLs have `#`. Any idea what is going wrong here?

**Comment by amir-zeldes** [comment] 2019-08-09 12:33
@thomaskrause

**Comment by amir-zeldes** [comment] 2019-08-09 12:38
OK, I can confirm that this affects GUM too if it is viewed under .../scriptorium/, so segmentations are not related to this.

**Comment by amir-zeldes** [comment] 2019-08-09 12:48
Update: the same bug affects coref (discourse) vis - it works without an instance name, and loads the ANNIS interface in a frame when used under an instance URL

**Comment by thomaskrause** [comment] 2019-08-15 12:09
This seems to be a duplicate of #581 and will affect all i-frame based visualizers. I would close this one as duplicate and leave the original bug open (which is apparently not fixed in ANNIS 4)

**Closed by thomaskrause** 2019-08-15 12:09 UTC

**Comment by amir-zeldes** [comment] 2019-08-15 17:42
Thanks and sorry about the duplicate - that's strange, I thought it was working. I can't remember how we addressed this, but the running ANNIS3 at GU doesn't have this problem. I see it's:

3.5.0-preview5 (rev. 20ffc21416, built 2017-10-09 11:48:10)

This and the rst vis bug are sadly blockers for upgrading the GU instance to graphANNIS...
