### ISSUE TITLE
Show context in "ref" KWIC view missing values  

### ISSUE THREAD

**Issue by lehmannx** [korpling/ANNIS#647] opened 2020-01-20 13:53 UTC
**Describe the bug**
In ANNIS 3.6 and earlier, we were able to select "Show context in = ref" in Search Options to produce a list of phrases that contain the search value – here the searched annotation value appears with all the rest of the phrase, but not more than the phrase boundary set by "ref". In ANNIS 4.0, the search result shows only the searched annotation value and none of the other elements inside the phrase.

**To Reproduce**
1. Go to 'ANNIS 4.0' corpus with KWIC view
2. Click on 'Search Option.'
3. Use "Show context in" to set it to reference instead of tokens
4. Set Right and Left context to 0
5. Search for an annotation that does not span the whole phrase

**Expected behavior**
KWIC view of searched value with all the annotations as part of the "Show in context" (here: ref).

**Screenshots**
ANNIS 4.0
![Screenshot 2020-01-20 at 14 49 20](https://user-images.githubusercontent.com/25769276/72731523-2e86b480-3b94-11ea-9024-a0cb336e4c3f.png)

ANNIS 3.6
![Screenshot 2020-01-20 at 14 48 22](https://user-images.githubusercontent.com/25769276/72731579-41998480-3b94-11ea-8a8b-8775337560c3.png)

**Desktop (please complete the following information):**
 - Operating System: [macOS]
 - Browser [safari]
 - Java Version: [e.g. OpenJDK 8, Oracle JDK 11 ???]
 - ANNIS Version [4.0]

**Comment by thomaskrause** [comment] 2020-02-03 10:19
I first thought you might be hitting the same bug as #624, this it should be fixed since the beta-3 release of ANNIS 4. Can you test your corpus with the latest snapshot version? I upload it to                                https://korpling.org/~thomas/annis-kickstarter-4.0.0-beta.4-SNAPSHOT-distribution.zip

I also tried to reproduce the problem with the RIDGES corpus using the "norm" layer as context and a match in dipl that is smaller, but in this case it works with the most recent version:

https://korpling.org/annis-beta/#_q=ZGlwbD0iQWxjaHniuJci&ql=aql&_c=UklER0VTX0hlcmJvbG9neV9WZXJzaW9uNi4w&cl=0&cr=0&s=0&l=10&_seg=bm9ybQ&_bt=ZGlwbA&

If the error is still happening in the kickstarter version provided above, I would need access to the corpus files to check what is happening.

**Comment by lehmannx** [comment] 2020-02-06 08:57
Hallo Thomas,

danke für die Rückmeldung.

Ich hatte den Fehler mit der Beta-Version 3 festgestellt. Die Snapshot-Version, die du mir geschickt hast, hat dafür ein anderes Problem, so dass ich das nicht testen konnte. Das Korpus lässt sich damit nit Importieren (es erscheint eine Fehlermeldung, die aber leer ist). Das Problem tritt auch bei älteren Dateien auf, die mit ANNIS immer funktioniert haben.

Ich hab dich auf Gitlab unserem Projekt hinzugefügt, da kannst du die Dateien herunterladen und es vielleicht einmal selbst ausprobieren.

Vielen Dank und viele Grüße,
Nico

**Comment by thomaskrause** [comment] 2020-03-26 15:29
I tested this with your corpus and the most up-to date graphANNIS version and the bug seems to be fixed. The fix will be included in the beta release

**Closed** 2020-03-26 15:45 UTC
Labels: bug
