### ISSUE TITLE
Query with more than one @* fails (Annis 4) 

### ISSUE THREAD

**Issue by gcelano** [korpling/ANNIS#833] opened 2023-07-10 14:40 UTC
**Describe the bug**

In Annis 4 desktop, a search like:

`tok  @* author=‎"Euripides‎" @* title=‎"Hippolytus‎"`

does not return anything (by mistake). The problem seems to be the presence of two `@*`, because each of them works without the other

**System:**
 - Operating System:  Ubuntu 22.04
 - Browser Chrome
 - Java Version: openjdk 11.0.19
 - ANNIS Version 4, desktop version

**Comment by thomaskrause** [comment] 2023-07-12 13:33
I think this should be 

```
tok  @* author=‎"Euripides‎" _ident_ title=‎"Hippolytus‎"
```

or alternatively

```
tok  & author=‎"Euripides‎" & title=‎"Hippolytus‎"
& #1 @* #2
& #1 @* #3
```

The `@*` means "part of" and both the author and title annotations are part of the same identical node. So with the initial query you would ask for a corpus structure like

```
                root-corpus
           /                    \
title=‎"Hippolytus‎"             [...]
          |
author=‎"Euripides‎"
          |
 tok tok tok tok
 ```

You can either just repeat the relation from the token to the document it is part of with two independent `@*` relations to the different metadata annotations, or explicitly state that both metadata annotations belong to the same document node (using the `_ident_` operator).

Since, as far as I understand the issue, is intended behavior, I would close this bug report. If I misunderstood or it does not answer your question please re-open the issue.

**Closed by thomaskrause** 2023-07-12 13:33 UTC
Labels: bug
