### ISSUE TITLE
Metadata View cannot be sorted other than alphabetically

### ISSUE THREAD

**Issue by fpetran** [korpling/ANNIS#500] opened 2016-03-01 16:30 UTC
It would be nice to be able to sort the metadata fields in the corpus information in another way than alphabetically.

**Comment by thomaskrause** [comment] 2020-02-03 12:24
Duplicate of #393

**Comment by thomaskrause** [comment] 2022-06-01 14:39
This is actually not a duplicate, because #393 is for the query results, not the metadata view

**Closed** 2022-06-03 10:40 UTC
Labels: enhancement
