### ISSUE TITLE
AQL-editor and bidirectional text

### ISSUE THREAD

**Issue by TFeige** [korpling/ANNIS#540] opened 2016-11-21 10:09 UTC
What is the used ANNIS version?
 3.4.4 (rev. b53ef2e654

What browser and operating system did you use?
Xubuntu 16.04 ; Firefox 49; Chromium 53

What steps will reproduce the problem?
1. Enter a  query like:   "علقة" & "مضغة" & #1 ^3,15 #2 (Actually it's not correct here, either.)
2. The problem is the handling of  e.g quotation marks and arabic text.
3.

What is the expected result?
Expected result would be the correct handling of mixed characters.

What happens instead?
The positioning of characters is not correct. Editing queries or entering new ones is really painful. 

Please provide any additional information below. Also please add a screenshot if possible.
As a workaround, we enter the query in an editor and copy-paste it into the AQL-editor.

![aql-window](https://cloud.githubusercontent.com/assets/19265315/20478447/6a53bdf8-afda-11e6-8627-1dcdb82cd50a.png)

**Comment by thomaskrause** [comment] 2016-11-24 08:42
Whow, the direction changes as soon as I type the first digit in `.1,15` and mixes everything up. I'm not even sure if this is any consistent text direction at all. In principle we once decided that we only want to have LTR in the query editor since the query syntax is LTR and only the content of single annotations might be RTL.

My current guess is that the syntax highlighting javascript library we use does something terrible wrong.

**Comment by thomaskrause** [comment] 2016-11-24 09:07
It's not the syntax highlighting library but the browsers itself. Any ```"<rtl>" .1``` entered in an HTML textarea is mixed up. I will investigate how I can enfore the correct behaviour.

**Comment by thomaskrause** [comment] 2016-11-24 14:38
@TFeige I'm still working my way through the W3C documentation about the intended behaviour of the textarea but there is a workaround that could help you:
The text direction of an textarea component is determined per line, thus if you write the annotation definitions containing RTL text as an extra line the display should work. E.g.
```
"<rtl>" ^1,15 "<rtl>"
```
would become
```
"<rtl>" 
^1,15 
"<rtl>"
```
or
```
"<rtl>" 
& <rtl>
& ^1,15 
""
```

**Comment by TFeige** [comment] 2016-11-28 10:33
Thank you! That makes searching indeed a bit easier.

**Comment by thomaskrause** [comment] 2017-06-30 10:27
We implemented a fix for this behaviour that works without the newline workaround. You can test it in our Experimental ANNIS-instance:

https://korpling.org/annis3-snapshot/?id=fe834c32-5085-4e65-bf82-b9805e626453

It should work in the latest versions of Firefox and Chrome, the latter one needs at least version 59 to work correctly. Also it works better if the opening and closing quotes (`"` or `/`) are written together since a non-closed string might confuse the Bidi-algoritms when editing on the fly.
Thanks a lot to @IrinaGlushanok  for the fix!

**Closed** 2017-10-09 08:14 UTC
Labels: bug
